config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, :controllers => { :registrations => 'admins/registrations' }
  resources :vehicle_models
  resources :vehicle_types
  resources :vehicle_brands
  resources :vehicles
  get 'add_preview/index/:id' => 'add_preview#index', as: 'add_preview'

  get 'dashboard/index' =>'dashboard#index', as: 'dashboard_path'

  get 'product/index'

  get 'product/new'

  get 'product/edit'

  get 'product/update'

  get 'product/destroy'

  get 'home_page/index'

  get 'ads/subcategories'

  root 'home_page#index'

  resources :services
  resources :feedbacks
  resources :emails
  resources :messages
  resources :comments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :locations
  resources :bookings
  resources :conversations
  resources :categories
  resources :companies
  devise_for :users
  resources :listings
  resources :ads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :ads_subcategory
  belongs_to :user, inverse_of: :ads
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
end

app/models/ads_subcategory.rb
class AdsSubcategory < ApplicationRecord
  belongs_to :category
  has_many :ads
end

app/models/booking.rb
class Booking < ApplicationRecord
has_many :listings
has_many :services
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :listings
  has_many :ads_subcategory
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :service
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :listings
  has_many :conversations
  has_many :emails
  has_many :location
  has_many :feedbacks
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :company
  # has_many :transactions
  has_many :messages

end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :user
  belongs_to :feedback
  belongs_to :company
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  has_many :emails
  belongs_to :company
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :company
  belongs_to :booking, optional: true
  has_many :messages
  has_many :locations
  # has_many :transactions
  has_many :comments
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :listing
  belongs_to :service
  belongs_to :user
  belongs_to :company
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :listing
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :booking
  has_many :comments
  belongs_to :user
  belongs_to :category
  # has_many :transactions
  has_many :locations

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  has_many :conversations
  has_one  :location
  has_many :emails
  has_many :feedbacks
  has_many :services
  has_many :ads

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/vehicle_brand.rb
class VehicleBrand < ApplicationRecord
  has_many :vehicle_model
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  belongs_to :vehicle_brand
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.where(user_id: current_user)
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :price, :description,
        :feature_image, :image_gallery, :availability, :address,
        :quantity, :currency, :user_id, :booking_id, :category_id,
        :company_id
      )
    end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/listings/_form.html.slim
= form_with(model: listing, local: true) do |form|
  - if listing.errors.any?
    #error_explanation
      h2
        = pluralize(listing.errors.count, "error")
        | prohibited this listing from being saved:
      ul
        - listing.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :title
    = form.text_field :title, id: :listing_title
  .field
    = form.label :price
    = form.number_field :price, id: :listing_price
  .field
    = form.label :description
    = form.text_area :description, id: :listing_description
  .field
    = form.label :feature_image
    = form.text_field :feature_image, id: :listing_feature_image
  .field
    = form.label :image_gallery
    = form.text_field :image_gallery, id: :listing_image_gallery
  .field
    = form.label :availability
    = form.check_box :availability, id: :listing_availability
  .field
    = form.label :address
    = form.text_area :address, id: :listing_address
  .field
    = form.label :quantity
    = form.number_field :quantity, id: :listing_quantity
  .field
    = form.label :currency
    = form.text_field :currency, id: :listing_currency
  .field
    = form.hidden_field :user_id, value: current_user.id
  .field
    = form.label :category
    = form.select :category_id, set_category.collect{|c|[c.name, c.id] }, {include_blank: true}, :class => 'form-control'
  .field
    = form.label :company
    = form.select :company_id, set_company.collect{|c|[c.name, c.id] }, {include_blank: true}, :class => 'form-control'
  /!
    | <div class="field"
    | <haml_loud> form.label :booking </haml_loud
    | <haml_loud> form.select :booking_id, set_booking.collect{|c|[c.appoiment, c.id] }, {include_blank: true}, :class =&gt; &#39;form-control&#39; </haml_loud
    | </div
  .actions
    = form.submit

app/views/listings/edit.html.slim
h1 Editing Listing
= render 'form', listing: @listing
= link_to 'Show', @listing
| \
= link_to 'Back', listings_path

app/views/listings/index.html.slim
p#notice= notice
- @listings.each do |listing|
  .jumbotron
    h1.display-4 q=""  Listings
    p.lead
      | Title: #{listing.title}
    hr.my-4/
    p
      | Price: #{listing.price}
    hr.my-4/
    p
      | Description: #{listing.description}
    hr.my-4/
    p
      | Feature Image: #{listing.feature_image}
    hr.my-4/
    p
      | Image Gallery: #{listing.image_gallery}
    hr.my-4/
    /! <p ><haml_loud> listing.availability </haml_loud></p
    p
      | Address: #{listing.address}
    hr.my-4/
    p
      | Quantity: #{listing.quantity}
    hr.my-4/
    p
      | Currency: #{listing.currency}
    hr.my-4/
    p= link_to 'Show', listing, class:'btn btn-primary btn-lg'
    p= link_to 'Edit', edit_listing_path(listing) , class:'btn btn-warning btn-lg'
    p= link_to 'Destroy', listing, method: :delete, data: {confirm: 'Are you sure?'}  , class:'btn btn-danger btn-lg'
= link_to 'New Listing', new_listing_path, class:'btn btn-primary'

app/views/listings/new.html.slim
.container
  .row.justify-content-center
    .col-12.col-lg-9
      h1.my-3 New Listing
      = render 'form', listing: @listing
      = link_to 'Back', listings_path, class: 'btn btn-primary'

app/views/listings/show.html.slim
p#notice= notice
.jumbotron
  h1.display-4 q="" 
  p.lead
    | Title: #{@listing.title}
  hr.my-4/
  p
    | Price: #{@listing.price}
  hr.my-4/
  p
    | Description: #{@listing.description}
  hr.my-4/
  p
    | Feature Image: #{@listing.feature_image}
  hr.my-4/
  p
    | Image Gallery: #{@listing.image_gallery}
  hr.my-4/
  /! <p ><haml_loud> @listing.availability </haml_loud></p
  p
    | Address: #{@listing.address}
  hr.my-4/
  p
    | Quantity: #{@listing.quantity}
  hr.my-4/
  p
    | Currency: #{@listing.currency}
= link_to 'Edit', edit_listing_path(@listing), class:'btn btn-warning btn-lg'
| \
= link_to 'Back', listings_path, class:'btn btn-primary btn-lg'