config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, :controllers => { :registrations => 'admins/registrations' }
  resources :vehicle_models
  resources :vehicle_types
  resources :vehicle_brands
  resources :vehicles
  get 'add_preview/index/:id' => 'add_preview#index', as: 'add_preview'

  get 'dashboard/index' =>'dashboard#index', as: 'dashboard_path'

  get 'product/index'

  get 'product/new'

  get 'product/edit'

  get 'product/update'

  get 'product/destroy'

  get 'home_page/index'

  get 'ads/subcategories'

  root 'home_page#index'

  resources :services
  resources :feedbacks
  resources :emails
  resources :messages
  resources :comments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :locations
  resources :bookings
  resources :conversations
  resources :categories
  resources :companies
  devise_for :users
  resources :listings
  resources :ads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :ads_subcategory
  belongs_to :user, inverse_of: :ads
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
end

app/models/ads_subcategory.rb
class AdsSubcategory < ApplicationRecord
  belongs_to :category
  has_many :ads
end

app/models/booking.rb
class Booking < ApplicationRecord
has_many :listings
has_many :services
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :listings
  has_many :ads_subcategory
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :service
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :listings
  has_many :conversations
  has_many :emails
  has_many :location
  has_many :feedbacks
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :company
  # has_many :transactions
  has_many :messages

end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :user
  belongs_to :feedback
  belongs_to :company
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  has_many :emails
  belongs_to :company
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :company
  belongs_to :booking, optional: true
  has_many :messages
  has_many :locations
  # has_many :transactions
  has_many :comments
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :listing
  belongs_to :service
  belongs_to :user
  belongs_to :company
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :listing
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :booking
  has_many :comments
  belongs_to :user
  belongs_to :category
  # has_many :transactions
  has_many :locations

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  has_many :conversations
  has_one  :location
  has_many :emails
  has_many :feedbacks
  has_many :services
  has_many :ads

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/vehicle_brand.rb
class VehicleBrand < ApplicationRecord
  has_many :vehicle_model
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  belongs_to :vehicle_brand
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:title, :message)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/conversations/_form.html.slim
= form_with(model: conversation, local: true) do |form|
  - if conversation.errors.any?
    #error_explanation
      h2
        = pluralize(conversation.errors.count, "error")
        | prohibited this conversation from being saved:
      ul
        - conversation.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :title
    = form.text_field :title, id: :conversation_title
  .field
    = form.label :message
    = form.text_area :message, id: :conversation_message
  .actions
    = form.submit

app/views/conversations/edit.html.slim
h1 Editing Conversation
= render 'form', conversation: @conversation
= link_to 'Show', @conversation
| \
= link_to 'Back', conversations_path

app/views/conversations/index.html.slim
p#notice= notice
h1 Conversations
table
  thead
    tr
      th Title
      th Message
      th colspan="3" 
  tbody
    - @conversations.each do |conversation|
      tr
        td= conversation.title
        td= conversation.message
        td= link_to 'Show', conversation
        td= link_to 'Edit', edit_conversation_path(conversation)
        td= link_to 'Destroy', conversation, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New Conversation', new_conversation_path

app/views/conversations/new.html.slim
h1 New Conversation
= render 'form', conversation: @conversation
= link_to 'Back', conversations_path

app/views/conversations/show.html.slim
p#notice= notice
p
  strong Title:
  = @conversation.title
p
  strong Message:
  = @conversation.message
= link_to 'Edit', edit_conversation_path(@conversation)
| \
= link_to 'Back', conversations_path