config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, :controllers => { :registrations => 'admins/registrations' }
  resources :vehicle_models
  resources :vehicle_types
  resources :vehicle_brands
  resources :vehicles
  get 'add_preview/index/:id' => 'add_preview#index', as: 'add_preview'

  get 'dashboard/index' =>'dashboard#index', as: 'dashboard_path'

  get 'product/index'

  get 'product/new'

  get 'product/edit'

  get 'product/update'

  get 'product/destroy'

  get 'home_page/index'

  get 'ads/subcategories'

  root 'home_page#index'

  resources :services
  resources :feedbacks
  resources :emails
  resources :messages
  resources :comments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :locations
  resources :bookings
  resources :conversations
  resources :categories
  resources :companies
  devise_for :users
  resources :listings
  resources :ads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :ads_subcategory
  belongs_to :user, inverse_of: :ads
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
end

app/models/ads_subcategory.rb
class AdsSubcategory < ApplicationRecord
  belongs_to :category
  has_many :ads
end

app/models/booking.rb
class Booking < ApplicationRecord
has_many :listings
has_many :services
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :listings
  has_many :ads_subcategory
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :service
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :listings
  has_many :conversations
  has_many :emails
  has_many :location
  has_many :feedbacks
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :company
  # has_many :transactions
  has_many :messages

end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :user
  belongs_to :feedback
  belongs_to :company
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  has_many :emails
  belongs_to :company
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :company
  belongs_to :booking, optional: true
  has_many :messages
  has_many :locations
  # has_many :transactions
  has_many :comments
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :listing
  belongs_to :service
  belongs_to :user
  belongs_to :company
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :listing
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :booking
  has_many :comments
  belongs_to :user
  belongs_to :category
  # has_many :transactions
  has_many :locations

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  has_many :conversations
  has_one  :location
  has_many :emails
  has_many :feedbacks
  has_many :services
  has_many :ads

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/vehicle_brand.rb
class VehicleBrand < ApplicationRecord
  has_many :vehicle_model
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  belongs_to :vehicle_brand
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :website, :addres, :phone_number, :company_type, :fbpage, :twitter, :employees, :rating)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/companies/_form.html.slim
= form_with(model: company, local: true) do |form|
  - if company.errors.any?
    #error_explanation
      h2
        = pluralize(company.errors.count, "error")
        | prohibited this company from being saved:
      ul
        - company.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :name
    = form.text_field :name, id: :company_name
  .field
    = form.label :website
    = form.text_field :website, id: :company_website
  .field
    = form.label :addres
    = form.text_area :addres, id: :company_addres
  .field
    = form.label :phone_number
    = form.text_field :phone_number, id: :company_phone_number
  .field
    = form.label :company_type
    = form.text_field :company_type, id: :company_company_type
  .field
    = form.label :fbpage
    = form.text_field :fbpage, id: :company_fbpage
  .field
    = form.label :twitter
    = form.text_field :twitter, id: :company_twitter
  .field
    = form.label :employees
    = form.text_field :employees, id: :company_employees
  .field
    = form.label :rating
    = form.number_field :rating, id: :company_rating
  .actions
    = form.submit

app/views/companies/edit.html.slim
h1 Editing Company
= render 'form', company: @company
= link_to 'Show', @company
| \
= link_to 'Back', companies_path

app/views/companies/index.html.slim
p#notice= notice
h1 Companies
table
  thead
    tr
      th Name
      th Website
      th Addres
      th Phone number
      th Company type
      th Fbpage
      th Twitter
      th Employees
      th Rating
      th colspan="3" 
  tbody
    - @companies.each do |company|
      tr
        td= company.name
        td= company.website
        td= company.addres
        td= company.phone_number
        td= company.company_type
        td= company.fbpage
        td= company.twitter
        td= company.employees
        td= company.rating
        td= link_to 'Show', company
        td= link_to 'Edit', edit_company_path(company)
        td= link_to 'Destroy', company, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New Company', new_company_path

app/views/companies/new.html.slim
h1 New Company
= render 'form', company: @company
= link_to 'Back', companies_path

app/views/companies/show.html.slim
p#notice= notice
p
  strong Name:
  = @company.name
p
  strong Website:
  = @company.website
p
  strong Addres:
  = @company.addres
p
  strong Phone number:
  = @company.phone_number
p
  strong Company type:
  = @company.company_type
p
  strong Fbpage:
  = @company.fbpage
p
  strong Twitter:
  = @company.twitter
p
  strong Employees:
  = @company.employees
p
  strong Rating:
  = @company.rating
= link_to 'Edit', edit_company_path(@company)
| \
= link_to 'Back', companies_path