config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, :controllers => { :registrations => 'admins/registrations' }
  resources :vehicle_models
  resources :vehicle_types
  resources :vehicle_brands
  resources :vehicles
  get 'add_preview/index/:id' => 'add_preview#index', as: 'add_preview'

  get 'dashboard/index' =>'dashboard#index', as: 'dashboard_path'

  get 'product/index'

  get 'product/new'

  get 'product/edit'

  get 'product/update'

  get 'product/destroy'

  get 'home_page/index'

  get 'ads/subcategories'

  root 'home_page#index'

  resources :services
  resources :feedbacks
  resources :emails
  resources :messages
  resources :comments
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :locations
  resources :bookings
  resources :conversations
  resources :categories
  resources :companies
  devise_for :users
  resources :listings
  resources :ads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :ads_subcategory
  belongs_to :user, inverse_of: :ads
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
end

app/models/ads_subcategory.rb
class AdsSubcategory < ApplicationRecord
  belongs_to :category
  has_many :ads
end

app/models/booking.rb
class Booking < ApplicationRecord
has_many :listings
has_many :services
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :listings
  has_many :ads_subcategory
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  belongs_to :service
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :listings
  has_many :conversations
  has_many :emails
  has_many :location
  has_many :feedbacks
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :company
  # has_many :transactions
  has_many :messages

end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :user
  belongs_to :feedback
  belongs_to :company
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  has_many :emails
  belongs_to :company
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :company
  belongs_to :booking, optional: true
  has_many :messages
  has_many :locations
  # has_many :transactions
  has_many :comments
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :listing
  belongs_to :service
  belongs_to :user
  belongs_to :company
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :listing
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :booking
  has_many :comments
  belongs_to :user
  belongs_to :category
  # has_many :transactions
  has_many :locations

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  has_many :conversations
  has_one  :location
  has_many :emails
  has_many :feedbacks
  has_many :services
  has_many :ads

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/models/vehicle_brand.rb
class VehicleBrand < ApplicationRecord
  has_many :vehicle_model
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  belongs_to :vehicle_brand
end

app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/categories/_form.html.slim
= form_with(model: category, local: true) do |form|
  - if category.errors.any?
    #error_explanation
      h2
        = pluralize(category.errors.count, "error")
        | prohibited this category from being saved:
      ul
        - category.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :name
    = form.text_field :name, id: :category_name
  .field
    = form.label :description
    = form.text_area :description, id: :category_description
  .actions
    = form.submit

app/views/categories/edit.html.slim
h1 Editing Category
= render 'form', category: @category
= link_to 'Show', @category
| \
= link_to 'Back', categories_path

app/views/categories/index.html.slim
p#notice= notice
h1 Categories
table
  thead
    tr
      th Name
      th Description
      th colspan="3" 
  tbody
    - @categories.each do |category|
      tr
        td= category.name
        td= category.description
        td= link_to 'Show', category
        td= link_to 'Edit', edit_category_path(category)
        td= link_to 'Destroy', category, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New Category
= render 'form', category: @category
= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice= notice
p
  strong Name:
  = @category.name
p
  strong Description:
  = @category.description
= link_to 'Edit', edit_category_path(@category)
| \
= link_to 'Back', categories_path